name: Deploy Ping Chart to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Terraform Init
      working-directory: ../challenge2/terraform-main-module
      run: terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ../challenge2/terraform-main-module
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ../challenge2/terraform-main-module
      run: terraform apply -input=false tfplan

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group resourceGroup --name cluster-test --overwrite-existing

    - name: Deploy Ping Chart with Helm
      run: |
        helm install ping ../challenge1/ping